<?php
class ClientArret {
  const TAB_DRAPEAU =
  [
    "Andorre" => 🇦🇩,
    "Belgique" =>🇧🇪,
    "Bénin" =>🇧🇯,
    "Bulgarie"=>🇧🇬,
    "Burkina Faso"=>🇧🇫,
    "Burundi"=>🇧🇮,
    "CADHP"=>⚪,
    "Cambodge"=>🇰🇭,
    "Cameroun"=>🇨🇲,
    "Canada"=>🇨🇦,
    "CEDEAO"=>⚪,
    "CEDH"=>⚪,
    "CEMAC"=>⚪,
    "Centrafrique"=>🇨🇫,
    "Comores"=>🇰🇲,
    "Congo"=>🇨🇬,
    "Congo démocratique"=>🇨🇩,
    "Côte d'Ivoire"=>🇨🇮,
    "France"=>🇫🇷,
    "Gabon" =>🇬🇦,
    "Guinée"=>🇬🇳,
    "Haïti"=>🇭🇹,
    "Hongrie"=>🇭🇺,
    "Liban"=>🇱🇧,
    "Luxembourg"=>🇱🇺,
    "Madagascar"=>🇲🇬,
    "Mali"=>🇲🇱,
    "Maroc"=>🇲🇦,
    "Mauritanie"=>🇲🇷,
    "Monaco"=>🇲🇨,
    "Niger"=>🇳🇪,
    "OEA"=>⚪,
    "OHADA"=>⚪,
    "Pologne"=>🇵🇱,
    "République Tchèque"=>🇨🇿,
    "Roumanie"=>🇷🇴,
    "Rwanda"=>🇷🇼,
    "Sao Tomé et Principe"=>🇸🇹,
    "Sénégal"=>🇸🇳,
    "Suisse"=>🇨🇭,
    "Tchad"=>🇹🇩,
    "Togo"=>🇹🇬,
    "Tunisie"=>🇹🇳,
    "UEMOA"=>⚪,
    "Vietnam"=>🇻🇳
  ];
}
?>
