# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: {module: recherche, action: index, query: ""}

#Solr Search
recherche:
  url: /recherche
  param: {module: recherche, action: index, query: ""}

recherche_filtres:
  url: /recherche_filtres
  param: {module: recherche, action: filtres}

recherche_resultats:
  url: /recherche/:query/:facets/:filter
  param: {module: recherche, action: search, query: "", facets: "", filter: ""}
  options:
    segment_separators: [/]

# Recherche avancée
recherche_avancee:
  url: /recherche_avancee
  param: {module: recherche, action: fullsearch, query: ""}

#Affichage des arrets
arretxml:
  url: /arret/:id/xml
  param: {module: arret, action: raw}

arrettxt:
  url: /arret/:id/txt
  param: {module: arret, action: raw, format: txt}

arretjson:
  url: /arret/:id/json
  param: {module: arret, action: raw, format: json}

arretmd:
  url: /arret/:id/md
  param: {module: arret, action: md}

arret:
  url: /arret/:id
  param: {module: arret, action: index}

admin_list:
   url: /admin/list
   param: {module: admin, action: list}

upload:
   url:  /admin/upload
   param: {module: admin, action: upload}

#Stats
stats:
  url: /stats
  param: {module: arret, action: stats}

#Actualités
actualites:
  url: /actualites
  param: {module: recherche, action: actualites}

static_partenaires:
  url: /static/partenaires
  param: {module: static, action: partenaires}
static_mentionslegales:
  url: /static/mentions_legales
  param: {module: static, action: mentionsLegales}
static_licenceodbl:
  url: /static/licence_odbl
  param: {module: static, action: licenceODBL}
static_licencejuricaf:
  url: /static/licence_juricaf
  param: {module: static, action: licenceJURICAF}
static_formmail:
  url: /static/form2mail
  param: {module: static, action: formMail}
static_donneespersonnelles:
  url: /static/donnees_personnelles
  param: {module: static, action: donneesPersonnelles}
static_contact:
  url: /static/contact
  param: {module: static, action: contact}
static_apropos:
  url: /static/a_propos
  param: {module: static, action: aPropos}



# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }
