<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/21 22:06:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=juricaf',
  'username' => 'root',
  'password' => '2sde1w1u',
  'name' => 'doctrine',
)),);
